import { bulkCreateResources } from "../server/db";
import type { InsertResource } from "../drizzle/schema";

const chapitre1Resources: InsertResource[] = [
  // Feuille de route
  {
    id: "ch1-feuille-route",
    chapterId: "chapitre-1",
    sectionId: "feuille-route",
    title: "Feuille de route - PRIX 4e",
    description: "Feuille de route du chapitre",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-Feuillederoute-PRIX4e.pdf",
    icon: "🗺️",
    visible: "true",
    order: "1",
  },
  // Cours
  {
    id: "ch1-cours",
    chapterId: "chapitre-1",
    sectionId: "cours",
    title: "Les Prix - Cours 4e",
    description: "Cours complet",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-LesPrix-Cours4e.pdf",
    icon: "📘",
    visible: "true",
    order: "1",
  },
  // Fiches techniques
  {
    id: "ch1-fiche-1",
    chapterId: "chapitre-1",
    sectionId: "fiches-techniques",
    title: "Fiche technique n°1 - Moyenne, médiane, étendue",
    description: "Statistiques de base",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-3-Fichetechniquen1-Moyennemdianeetendue.pdf",
    icon: "📊",
    visible: "true",
    order: "1",
  },
  {
    id: "ch1-fiche-2",
    chapterId: "chapitre-1",
    sectionId: "fiches-techniques",
    title: "Fiche technique n°2 - Proportionnalité, Pourcentages",
    description: "Calculs de proportionnalité",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-4-Fichetechniquen2-ProportionnalitPourcentages.pdf",
    icon: "📊",
    visible: "true",
    order: "2",
  },
  {
    id: "ch1-fiche-3",
    chapterId: "chapitre-1",
    sectionId: "fiches-techniques",
    title: "Fiche technique n°3 - Calcul littéral 1ère Partie",
    description: "Introduction au calcul littéral",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-5-Fichetechniquen3-Calcullittral1rePartie.pdf",
    icon: "📊",
    visible: "false",
    order: "3",
  },
  // Aides techniques
  {
    id: "ch1-aide-1",
    chapterId: "chapitre-1",
    sectionId: "fiches-techniques",
    title: "Aide technique n°1 - Moyenne, médiane, étendue",
    description: "Aide pour les statistiques",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-3.1-Aidetechniquen1-Moyennemdianeetendue.pdf",
    icon: "💡",
    visible: "true",
    order: "4",
  },
  {
    id: "ch1-aide-2",
    chapterId: "chapitre-1",
    sectionId: "fiches-techniques",
    title: "Aide technique n°2 - Proportionnalité, Pourcentages",
    description: "Aide pour la proportionnalité",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-4.1-Aidetechniquen2-ProportionnalitPourcentages.pdf",
    icon: "💡",
    visible: "false",
    order: "5",
  },
  // Exercices
  {
    id: "ch1-exercices",
    chapterId: "chapitre-1",
    sectionId: "exercices",
    title: "Feuille d'exercices Les Prix 4e",
    description: "Exercices d'application",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-FeuilledexercicesLesPrix4e1.pdf",
    icon: "✏️",
    visible: "false",
    order: "1",
  },
  // Situations
  {
    id: "ch1-sit-1",
    chapterId: "chapitre-1",
    sectionId: "activites",
    title: "Situation n°1 - Prix immobilier à Lyon",
    description: "Étude de cas immobilier",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-1-Situation-PriximmobilierLyon.pdf",
    icon: "🏠",
    visible: "false",
    order: "1",
  },
  {
    id: "ch1-sit-2",
    chapterId: "chapitre-1",
    sectionId: "activites",
    title: "Situation n°2 - Côte de cochon",
    description: "Étude de prix alimentaires",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-2-Situation-Ctedecochon.pdf",
    icon: "🥩",
    visible: "false",
    order: "2",
  },
  {
    id: "ch1-sit-3",
    chapterId: "chapitre-1",
    sectionId: "activites",
    title: "Situation n°3 - Location trottinette",
    description: "Comparaison de tarifs",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-3-Situation-Locationtrottinette.pdf",
    icon: "🛴",
    visible: "false",
    order: "3",
  },
  {
    id: "ch1-sit-4",
    chapterId: "chapitre-1",
    sectionId: "activites",
    title: "Situation n°4 - Évolution Prix fruits et légumes",
    description: "Analyse d'évolution de prix",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-4-Situation-EvolutionPrixfruitsetlgumes.pdf",
    icon: "🍎",
    visible: "false",
    order: "4",
  },
  {
    id: "ch1-sit-5",
    chapterId: "chapitre-1",
    sectionId: "activites",
    title: "Situation n°5 - Impôt sur le revenu",
    description: "Calculs fiscaux",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-5-Situation-Imptsurlerevenu.pdf",
    icon: "💰",
    visible: "false",
    order: "5",
  },
  {
    id: "ch1-sit-6",
    chapterId: "chapitre-1",
    sectionId: "activites",
    title: "Situation n°6 - Location de DVD",
    description: "Comparaison d'abonnements",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-6-Situation-LocationdeDVD.pdf",
    icon: "📀",
    visible: "false",
    order: "6",
  },
  {
    id: "ch1-sit-7",
    chapterId: "chapitre-1",
    sectionId: "activites",
    title: "Situation n°7 - Mise en place calcul littéral et résolution d'équations",
    description: "Introduction aux équations",
    type: "pdf",
    url: "https://s3.manus.space/user-uploads/1761569451623-7-Miseenplacecalcullittralersolutiondquations.pdf",
    icon: "🔢",
    visible: "false",
    order: "7",
  },
];

console.log(`Ajout de ${chapitre1Resources.length} ressources pour le Chapitre 1...`);
await bulkCreateResources(chapitre1Resources);
console.log("✅ Chapitre 1 ajouté avec succès !");
process.exit(0);

